server:
  port: 8888
spring:
  application:
    name: Taskify
  datasource:
    url: jdbc:postgresql://localhost:5433/taskify
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
