server:
  port: 8888
spring:
  application:
    name: Taskify
  datasource:
    url: jdbc:postgresql://localhost:5433/taskify
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
springdoc:
  api-docs:
    path: /api-docs
    pathsToMatch: /api/**
  swagger-ui:
    use-root-path: true
    path: /docs-ui
